### ISSUE TITLE
Create NLM About page

### ISSUE THREAD

**Issue by Negative-light** [negative-light-media/www.negative-light.com#14]
Create a page called NLM about. That should inform people about what is going on.

**Comment by crazysmile11012** [comment]
il do that

**Comment by Negative-light** [comment]
K big thing is removing the alert from the about and adding that text there.
Once this is done shouldn't be hard

**Comment by crazysmile11012** [comment]
> K big thing is removing the alert from the about and adding that text there. Once this is done shouldn't be hard

done btw
