### ISSUE TITLE
Move to a github workflow design

### ISSUE THREAD

**Issue by Negative-light** [negative-light-media/www.negative-light.com#25]
The goal is to make a github workflow that operates the website. I am not certain how this will work but i will look into it.

**Comment by Negative-light** [comment]
I will experiment on a private repo for a bit to see what we can do

**Comment by Negative-light** [comment]
Should we add in React?
Do plain old HTML?
@DanPace725 and @crazysmile11012 what are y'alls thoughts?

**Comment by Negative-light** [comment]
This could be interesting.
[Video on Next.js](https://www.youtube.com/watch?v=Sklc_fQBmcs)

**Comment by crazysmile11012** [comment]
id prefer plain html with node.js but i won't stop you from using react

**Comment by crazysmile11012** [comment]
i can always learn a new framework but the quality may not be as high as normal html from me

**Comment by Negative-light** [comment]
I can see if there is a Node.js build. I agree that using a framework can add unnecessary build steps.

**Comment by crazysmile11012** [comment]
k

**Comment by Negative-light** [comment]
Node.js is a server side so we cannot use that.
So the question is do we just want to go plain HTML, CSS, or add react for some plugins and support?
React is a common framework so if you are doing work for a normal company you are probably going to use it.
Jekell could be used for things like the NLM page and stuff and this one can use common API's to run the Negative_light side of things

**Comment by crazysmile11012** [comment]
lets add the plugins, il learn them but for a while il mostly do html & css

**Comment by DanPace725** [comment]
I'm for React, it's got lots of support and will be supported for awhile from what I can tell. The trade off being it's more complicated than html and there might be a learning curve and thus extend the amount of time it'll take to get to a finished product.

**Comment by Negative-light** [comment]
Ok, should we pull in a basic react app template that we can then modify to appear like the current Repo?

**Comment by crazysmile11012** [comment]
we should do it on the working branch so we don't mess up development if it does not work

**Comment by crazysmile11012** [comment]
we also can make a new repo for messing around and learning the workflow of react

**Comment by Negative-light** [comment]
I agree on both fronts.
So lets 
1. make a branch `working-react-move`
2. Make a separate project (should we do it here or just make one in my personal thing) for us to build up the workflow and fiddle with it.

I did notice that there are ways to change the branch that it builds off of and this would allow us to do checks on pushes to development as well.

**Comment by crazysmile11012** [comment]
i agree
@DanPace725  u game?

**Comment by DanPace725** [comment]
Sounds good to me.

**Comment by Negative-light** [comment]
Ok i will get started on this

**Comment by Negative-light** [comment]
I think i have it there not sure yet. We will ahve to make some changes of course
