### ISSUE TITLE
Add Contributors Page

### ISSUE THREAD

**Issue by Negative-light** [negative-light-media/www.negative-light.com#32]
# Purpose

The purpose of this issue is to add a page that lists all the contributors to the website itself. This would just be a generic list that maybe includes their github

# Design

There are several ways to do this including but not limited to
1. Hard Coding it (Easy to build up but harder to maintain)
2. Have each Contributor add themselves manually (Easy to build and Maintain)
3. Add an automated script that would collect all contributors to the website and list them out (Easy to maintain & reduces the chance for mistakes)

**Comment by Negative-light** [comment]
There is [Documentation](https://docs.github.com/en/free-pro-team@latest/rest/repos/repos?apiVersion=2022-11-28#list-repository-contributors) for GitHub REST API that should allow us to query the contributors easily.

**Comment by Negative-light** [comment]
I think that this fits best in the initial release

**Comment by Negative-light** [comment]
![sugested contributors page](https://github.com/negative-light-media/www.negative-light.com/assets/53065989/9eb2570c-2f4a-45ff-a5fd-761f99196ee8)
This could be a good layout for the contributor's page. It would be contribution organized. Maybe we add a file that includes different roles too.

**Comment by Negative-light** [comment]
A good question is if this should be queried from Github OR added directly into a *.md file?

I think it would be best to see what other groups do.

**Comment by crazysmile11012** [comment]
queried would be ideal
imo it should log all contributions in nlm
it should order them from most contributions to least tbh

**Comment by crazysmile11012** [comment]
there should also be "metals" like something you earn at commit milestones
also if nlm will have account login it should authorize via github so it can put ur accounts score on a div menu above so u don't have to scroll for hours to see ur position

**Comment by crazysmile11012** [comment]
your stats:
------------------------------------------
(pfp)" github name" commits: "7" ()<--metals
---------------------------------------
leaderboard:
-------------------------------------------
1. (pfp)" github name" commits: "234" ()()()()
2. (pfp)" github name" commits: "70" ()()()
3. (pfp)" github name" commits: "56" ()()
esc...

**Comment by Negative-light** [comment]
That could be cool when we move to a full site. Could include overall contributions for all projects.
we also need to make the `media.negative-light.com` site at some point too that will have all of its contributors and such listed as well. Then we have kinda have Project level and Organization level contributions and such. That would be cool

**Comment by crazysmile11012** [comment]
to see contributions u don't need to login but to view ur stats (if u have some) u need to login

**Comment by Negative-light** [comment]
Well to easily view your stats

**Comment by crazysmile11012** [comment]
yup

**Comment by crazysmile11012** [comment]
how do we do this and keep it a static page
Update html file itself?

**Comment by crazysmile11012** [comment]
we need to host it on a pi or somethin

**Comment by crazysmile11012** [comment]
![image](https://github.com/negative-light-media/www.negative-light.com/assets/107813207/94f924ce-5cd5-4df9-9eff-37540d5157c4)

**Comment by Negative-light** [comment]
So contributors can be updated on a build as you have to make code changes for this repo for you to be added.
Therefore it will be a list of people who have contributed to the Current website for now.
The other bits yeah we need to setup hosting which I might be able to do soon ish (TM)

**Comment by crazysmile11012** [comment]
the question "is it supported?"

**Comment by crazysmile11012** [comment]
like use git actions to autoupload to the server u choose

**Comment by Negative-light** [comment]
I think the first query is. But after that no.
We can make stuff that is dynamic be Iframes in other repos though.

**Comment by crazysmile11012** [comment]
iframes are PAIN

**Comment by Negative-light** [comment]
Agreed

**Comment by Negative-light** [comment]
[This](https://github.com/mgechev/github-contributors-list/) might be something we can use. Pull the contributors on build put it in a table and then write it out. From there we can add more.
