### ISSUE TITLE
Add Buy me a coffee Embeed

### ISSUE THREAD

**Issue by Negative-light** [negative-light-media/www.negative-light.com#39]
First, should we even do this?
Second if we do lets use the custom one that is easy to work with.

**Comment by crazysmile11012** [comment]
i think u need all the financial support u can get

**Comment by crazysmile11012** [comment]
il do my best

**Comment by Negative-light** [comment]
THat is valid. We will be adding stuff like that for the website development at some point too. Need to research how that works and setup the legal end of things there. This one would be for my YT channel. Then if we add one for NLM it will be for NLM
