### ISSUE TITLE
style and layout of webpage

### ISSUE THREAD

**Issue by crazysmile11012** [negative-light-media/www.negative-light.com#6]
i have a few ideas for layouts & styles that need enhancement and feedback before we advance

**Comment by anujnamdeo** [comment]
tf

**Comment by crazysmile11012** [comment]
il start of by making a basic layout with the @Negative-light official color pallet

**Comment by Negative-light** [comment]
This would also be related to #10

**Comment by Negative-light** [comment]
I believe this is complete
